# Generated by Django 2.0 on 2017-12-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propositions',
            old_name='awnser',
            new_name='answer',
        ),
    ]
